# Generated by Django 2.2.1 on 2019-05-28 17:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travel_buddy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='travelend',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travel',
            name='travelstart',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
